---
name: "Deploy site"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "master"
  workflow_dispatch:
    # Allow manually running workflow
  schedule:
    - cron: "23 2 * * *"

env:
  DEPLOY: >-
    ${{
    github.event_name != 'pull_request'
    &&
    github.ref == 'refs/heads/master'
    }}
  OUTPUT: _html
  LEKTOR_DIR: ./dovydas.xyz
  SSH_FILENAME: id_rsa

jobs:
  build:
    name: Build lektor website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install Lektor
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install lektor
      - name: Build lektor website
        working-directory: "${{ env.LEKTOR_DIR }}"
        run: lektor build -O "${{ env.OUTPUT }}"

      - name: Check for broken internal links
        uses: wjdp/htmltest-action@master
        with:
          path: "${{ env.LEKTOR_DIR }}/${{ env.OUTPUT }}"
          config: .htmltest.yml
          skip_external: true
          log_level: 1
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: "${{ secrets.SSH_DEP_KEY }}"
          name: "${{ env.SSH_FILENAME }}" # optional
          if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
          # known_hosts: ${{ secrets.KNOWN_HOSTS }}
          # config: ${{ secrets.CONFIG }} # ssh_config; optional

      - name: Deploy lektor website
        working-directory: "${{ env.LEKTOR_DIR }}"
        if: env.DEPLOY == 'true'
        run: lektor deploy --key-file "${{ env.SSH_FILENAME }}" -O "${{ env.LEKTOR_DIR }}/${{ env.OUTPUT }}" ghpages
